### ISSUE TITLE
Crash when renaming Tetra sword

### ISSUE THREAD

**Issue by Madchomp** [PORTB/chat-colours#1]
Whenever I hover over my sword after typing "§[gold]Sword" it crashes. I did successfully rename my pickaxe and mattock without any issues.
[crash-2022-01-11_12.44.22-client.txt](https://github.com/PORTB/chat-colours/files/7846225/crash-2022-01-11_12.44.22-client.txt)

**Comment by PORTB** [comment]
You need to update your iceberg library (used by legendary tooltips) to
1.0.33, which fixes this crash
